services:
  postgres:
    image: postgres:15
    container_name: hl7-postgres
    environment:
      POSTGRES_DB: hl7_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./fastapi-backend/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 180s
      timeout: 10s
      retries: 5

  backend:
    build: 
      context: ./fastapi-backend
      dockerfile: Dockerfile
    container_name: hl7-backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/hl7_db
      PYTHONPATH: /app
    volumes:
      - ./fastapi-backend/uploads:/app/uploads
      - ./fastapi-backend/sample_files:/app/sample_files
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hl7-frontend
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    command: npm run dev -- --host 0.0.0.0

  nginx:
    image: nginx:alpine
    container_name: hl7-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data: