"""add_patient_name_and_medical_document_fields

Revision ID: 0475981f085b
Revises: 2d97c9842ca9
Create Date: 2025-09-27 21:43:14.681668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0475981f085b'
down_revision = '2d97c9842ca9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_conversions', sa.Column('plain_english', sa.Text(), nullable=True))
    op.add_column('saved_conversions', sa.Column('latex_content', sa.Text(), nullable=True))
    op.add_column('saved_conversions', sa.Column('html_content', sa.Text(), nullable=True))
    op.add_column('saved_conversions', sa.Column('pdf_base64', sa.Text(), nullable=True))
    op.add_column('saved_conversions', sa.Column('patient_name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_conversions', 'patient_name')
    op.drop_column('saved_conversions', 'pdf_base64')
    op.drop_column('saved_conversions', 'html_content')
    op.drop_column('saved_conversions', 'latex_content')
    op.drop_column('saved_conversions', 'plain_english')
    # ### end Alembic commands ###