"""Add SavedConversion table

Revision ID: 2ae880efafd4
Revises: 
Create Date: 2025-09-27 04:36:29.486267

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2ae880efafd4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hl7_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('raw_hl7_content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=10), nullable=False),
    sa.Column('trigger_event', sa.String(length=10), nullable=True),
    sa.Column('patient_id', sa.String(length=50), nullable=True),
    sa.Column('xml_content', sa.Text(), nullable=True),
    sa.Column('json_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pdf_content', sa.LargeBinary(), nullable=True),
    sa.Column('processing_status', sa.String(length=20), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('patient_first_name', sa.String(length=100), nullable=True),
    sa.Column('patient_last_name', sa.String(length=100), nullable=True),
    sa.Column('patient_dob', sa.DateTime(), nullable=True),
    sa.Column('patient_gender', sa.String(length=1), nullable=True),
    sa.Column('visit_number', sa.String(length=50), nullable=True),
    sa.Column('admission_date', sa.DateTime(), nullable=True),
    sa.Column('discharge_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_conversions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_hl7_content', sa.Text(), nullable=False),
    sa.Column('json_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('xml_content', sa.Text(), nullable=True),
    sa.Column('conversion_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processing_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=True),
    sa.Column('processing_step', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['hl7_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visit_data')
    op.drop_table('processing_logs')
    op.drop_table('patient_data')
    op.drop_table('observation_data')
    op.drop_table('allergy_data')
    op.drop_table('saved_conversions')
    op.drop_table('hl7_messages')
    # ### end Alembic commands ###