"""Add SavedConversion table

Revision ID: 2ae880efafd4
Revises: 
Create Date: 2025-09-27 04:36:29.486267

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2ae880efafd4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hl7_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('raw_hl7_content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=10), nullable=False),
    sa.Column('trigger_event', sa.String(length=10), nullable=True),
    sa.Column('patient_id', sa.String(length=50), nullable=True),
    sa.Column('xml_content', sa.Text(), nullable=True),
    sa.Column('json_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pdf_content', sa.LargeBinary(), nullable=True),
    sa.Column('processing_status', sa.String(length=20), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('patient_first_name', sa.String(length=100), nullable=True),
    sa.Column('patient_last_name', sa.String(length=100), nullable=True),
    sa.Column('patient_dob', sa.DateTime(), nullable=True),
    sa.Column('patient_gender', sa.String(length=1), nullable=True),
    sa.Column('visit_number', sa.String(length=50), nullable=True),
    sa.Column('admission_date', sa.DateTime(), nullable=True),
    sa.Column('discharge_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_conversions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_hl7_content', sa.Text(), nullable=False),
    sa.Column('json_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('xml_content', sa.Text(), nullable=True),
    sa.Column('conversion_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('allergy_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('allergen_type', sa.String(length=50), nullable=True),
    sa.Column('allergen_code', sa.String(length=100), nullable=True),
    sa.Column('allergen_description', sa.String(length=200), nullable=True),
    sa.Column('allergy_severity', sa.String(length=20), nullable=True),
    sa.Column('allergy_reaction', sa.Text(), nullable=True),
    sa.Column('allergy_type', sa.String(length=50), nullable=True),
    sa.Column('allergy_status', sa.String(length=20), nullable=True),
    sa.Column('identification_date', sa.DateTime(), nullable=True),
    sa.Column('onset_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['hl7_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observation_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('observation_id', sa.String(length=100), nullable=True),
    sa.Column('observation_set_id', sa.String(length=100), nullable=True),
    sa.Column('value_type', sa.String(length=10), nullable=True),
    sa.Column('observation_identifier', sa.String(length=200), nullable=True),
    sa.Column('observation_name', sa.String(length=200), nullable=True),
    sa.Column('observation_value', sa.Text(), nullable=True),
    sa.Column('units', sa.String(length=50), nullable=True),
    sa.Column('reference_range', sa.String(length=100), nullable=True),
    sa.Column('abnormal_flags', sa.String(length=20), nullable=True),
    sa.Column('result_status', sa.String(length=10), nullable=True),
    sa.Column('observation_date', sa.DateTime(), nullable=True),
    sa.Column('collection_date', sa.DateTime(), nullable=True),
    sa.Column('responsible_observer', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['hl7_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.String(length=50), nullable=True),
    sa.Column('mrn', sa.String(length=50), nullable=True),
    sa.Column('ssn', sa.String(length=11), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('race', sa.String(length=100), nullable=True),
    sa.Column('ethnicity', sa.String(length=100), nullable=True),
    sa.Column('marital_status', sa.String(length=20), nullable=True),
    sa.Column('address_line1', sa.String(length=200), nullable=True),
    sa.Column('address_line2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('phone_home', sa.String(length=20), nullable=True),
    sa.Column('phone_work', sa.String(length=20), nullable=True),
    sa.Column('phone_mobile', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=200), nullable=True),
    sa.Column('emergency_contact_relationship', sa.String(length=50), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['hl7_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processing_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=True),
    sa.Column('processing_step', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['hl7_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visit_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('visit_number', sa.String(length=50), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('patient_class', sa.String(length=20), nullable=True),
    sa.Column('admission_type', sa.String(length=50), nullable=True),
    sa.Column('admission_date', sa.DateTime(), nullable=True),
    sa.Column('discharge_date', sa.DateTime(), nullable=True),
    sa.Column('assigned_location', sa.String(length=100), nullable=True),
    sa.Column('room_number', sa.String(length=20), nullable=True),
    sa.Column('bed_number', sa.String(length=20), nullable=True),
    sa.Column('attending_doctor', sa.String(length=200), nullable=True),
    sa.Column('referring_doctor', sa.String(length=200), nullable=True),
    sa.Column('consulting_doctor', sa.String(length=200), nullable=True),
    sa.Column('discharge_disposition', sa.String(length=100), nullable=True),
    sa.Column('discharge_location', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['hl7_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visit_data')
    op.drop_table('processing_logs')
    op.drop_table('patient_data')
    op.drop_table('observation_data')
    op.drop_table('allergy_data')
    op.drop_table('saved_conversions')
    op.drop_table('hl7_messages')
    # ### end Alembic commands ###